name: Playwright Tests
on: # Trigger condition, trigger workflow after master branch push code
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 * * 6'
    - cron: '5 * * * *' 
#  push:
#    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
